version: '3'
services: 
  mongodb: 
    image: 'bitnami/mongodb:latest'
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root123
    ports: 
      - '27017:27017'
    volumes: 
      - 'mongo-db:/bitnami/mongodb'
    
  redis: 
    image: redis:alpine
    container_name: redis
    restart: always
    ports: 
      - '6379:6379'
    volumes: 
      - 'redis:/data'

volumes:
  mongo-db:
  redis:

